Revert changes to CaddyConfig set up. (#846)
Saw some changes in [this commit] that messed with the CaddyConfig, causing SSL errors:

```
Shared connection to 54.86.192.143 closed.
/Users/rohinbhasin/work/runhouse/runhouse/servers/http/http_client.py:115: UserWarning: Cert in use (/Users/rohinbhasin/.rh/certs/rh_server.crt) is self-signed, cannot independently verify it.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/site-packages/requests/adapters.py", line 589, in send
    resp = conn.urlopen(
  File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='54.86.192.143', port=443): Max retries exceeded with url: /resource/ (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rohinbhasin/work/mine/den_auth_tls.py", line 4, in <module>
    den_auth_cluster = rh.cluster(name="tls-manual-commit-fixed",
  File "/Users/rohinbhasin/work/runhouse/runhouse/resources/hardware/cluster.py", line 380, in up_if_not
    self.up()
  File "/Users/rohinbhasin/work/runhouse/runhouse/resources/hardware/on_demand_cluster.py", line 443, in up
    self.restart_server()
  File "/Users/rohinbhasin/work/runhouse/runhouse/resources/hardware/cluster.py", line 892, in restart_server
    self.put_resource(self.default_env)
  File "/Users/rohinbhasin/work/runhouse/runhouse/resources/hardware/cluster.py", line 550, in put_resource
    return self.client.put_resource(
  File "/Users/rohinbhasin/work/runhouse/runhouse/servers/http/http_client.py", line 553, in put_resource
    return self.request_json(
  File "/Users/rohinbhasin/work/runhouse/runhouse/servers/http/http_client.py", line 229, in request_json
    response = retry_with_exponential_backoff(req_fn)(
  File "/Users/rohinbhasin/work/runhouse/runhouse/servers/http/http_client.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/rohinbhasin/miniconda3/envs/rh-env/lib/python3.9/site-packages/requests/adapters.py", line 620, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='54.86.192.143', port=443): Max retries exceeded with url: /resource/ (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1129)')))
```